### PR TITLE
Added ability to switch windows using touch screen

### LINKED ISSUE #50: Touchscreen doesn't switch window
I'm not sure if this is a bug or just a not yet implemented feature but when I try to select a window using the touchscreen it just takes me back to the previous window I was using. I can switch desktops via the touchscreen and I can move windows between desktops, so it is just window selection that doesn't work.

### PR DESCRIPTION
**Pull request by samkottler**
resolves #50

### CODE REVIEW

**Comment by tcorreabr** [comment]
I had already tried to move TapHandler from ScreenComponent to DesktopComponent, but this brings some unwanted side-effects related to keyboard selection or clicking on an empty desktop area to exit Parachute. But I saw that you had the idea to add the "case Qt.NoButton" in the onTapped event, and maybe that alone will solve the error of not responding to a touch. Can you test this since I don't use a touchscreen device?

**Comment by samkottler** [comment]
As far as I can tell the touchsceen handler has to be in DesktopComponent because otherwise it can't figure out which window is actually selected. That being said, I don't think that my commit breaks anything with keyboard selection. The only thing is that seems to be broken is that clicking somewhere with no window doesn't close the overlay anymore. I will fix this.

**Comment by tcorreabr** [comment]
I am trying another way to move the two TapHandlers of ScreenComponent to only one in DesktopComponent. I think the code would improve that way. Can you confirm if "case Qt.NoButton" works for touchscreens? I haven't found proper documentation on this. Thanks for your contribution.

**Comment by samkottler** [comment]
On my touch screen Qt.NoButton works but I'm not sure it will work for all touch screens. However, it will also potentially use that for other input devices too. I think maybe a better solution would be to have separate cases based on which input device was used. When I modified my commit I did this by making the tap handler ignore touchscreen events and making a separate one that only accepts touchscreen events. I think you could also look at event.device and have separate cases for DeviceType.mouse and DeviceType.touchScreen. This way you could avoid having to handle Qt.NoButton.

**Comment by tcorreabr** [comment]
For now I will avoid creating another TapHandler and will just treat Qt.NoButton. If the problem persists in any way, I will recover your code. Thanks!

**Pull request closed without merging**
